name: detgas_1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.10.0

  firebase_core: ^1.3.0

  firebase_messaging: ^10.0.2
  flutter_local_notifications: ^5.0.0+4
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  firebase_database: ^7.1.1

  firebase_auth: ^1.4.1
  # google_sign_in:
  # apple_sign_in:

  provider: ^5.0.0
  shared_preferences: ^2.0.6
  # upstate:

  flutter_platform_widgets: ^1.9.5
  flutter_sheet_localization: ^5.1.1
  simple_gravatar: ^1.1.0
  # flutter_auth_buttons:

  bottom_navy_bar: ^6.0.0

  flutter_animation_progress_bar: ^1.0.0

  #marquee
  marquee: ^2.2.0

  bubble_tab_indicator: ^0.1.6
  fl_chart: ^0.36.2

  url_launcher: ^6.0.7

  r_flutter: ^0.8.0
  
  #maps
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^5.1.7
  build_runner: ^2.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: Pacifico 
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
      
    - family: Source Sans Pro
      fonts: 
        - asset: assets/fonts/SourceSansPro-Regular.ttf
    
    - family: Oswald
      fonts: 
        - asset: assets/fonts/Oswald-Regular.ttf

    - family: PTS
      fonts: 
        - asset: assets/fonts/PTS56F.ttf